config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users 

  root 'pages#home'
  
  resources :users , only: [:show,:index]
  resources :friendships , only: [:create,:destroy,:accept] do
    member do
      put :accept
    end
  end  
  
  resources :posts , only: [:create,:edit,:update,:destroy]
  resources :activities , only: [:index]
    

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  include PublicActivity::Model
    belongs_to :user
    belongs_to :friend , class_name: "User"
    
    def accept_friendship
      self.update_attributes(state: "active",friended_at: Time.now)  
    end
    
    def deny_friendship
      self.destroy    
    end
    
    def cancel_friendship
       self.destroy    
    end    
    
end

app/models/post.rb
class Post < ActiveRecord::Base
    include PublicActivity::Model
    belongs_to :user
    
    validates_presence_of :user_id
    validates_presence_of :content
    
    auto_html_for :content do
        html_escape
        image
        youtube(width: "100%" , height: 250, autoplay: false)
        link target: "_blank", rel: "nofollow"
        simple_format
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_presence_of :username
  validates_uniqueness_of :username
  
  has_many :friendships , dependent: :destroy
  has_many :inverse_friendships , class_name: "Friendship" , foreign_key: "friend_id", dependent: :destroy
  has_many :posts , dependent: :destroy
  
  def request_friendship(u2)
    self.friendships.create(friend: u2)
  end  
  
  def pending_request_from #we haven't confirmed this friendship
    self.inverse_friendships.where(state: "pending")
  end  
  
  def pending_request_to
    self.friendships.where(state: "pending")
  end
  
  def active_friends
    self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end 
  
  def friendship_status(u2)
    
    friendship = Friendship.where(user_id: [self.id,u2.id] , friend_id: [self.id,u2.id])
    
    unless friendship.any?
      return "not_friends"
    else
      if friendship.first.state == "active"
        return "friends"
      else
      if friendship.first.user == self
        return "pending"
      else
        return "requested"
      end 
      end
      
    end    
    
  end  
  
  def friendship_relation(u2)
    Friendship.where(user_id: [self.id,u2.id] , friend_id: [self.id,u2.id]).first
  end  
  
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :authenticate_user!,  only: [:index]
    
    def index
       @user =  current_user.active_friends
       @user.push(current_user)
       case params[:content] when 'posts'
            @activities = PublicActivity::Activity.where(owner_id: @user, trackable_type: "Post").order('created_at DESC')
       else
           @activities = PublicActivity::Activity.where(owner_id: @user).order('created_at DESC')
       end    
    end    
    
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    
  helper_method :friend_request_count
      
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up , keys: [:username ,:age,:gender,:bio])
   devise_parameter_sanitizer.permit(:sign_in , keys: [:username ])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username ,:age,:gender,:bio])
  end
  
  def friend_request_count
      current_user.pending_request_from.map(&:user).size
  end      
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
   before_action :authenticate_user!
   before_action :set_user, only: [:create]
   before_action :set_friendship, only: [:destroy , :accept]
   
   
   
   def create
       @friendship = current_user.request_friendship(@user)
       respond_to do |format|
           format.html {redirect_to users_path, notice: "Friendship Created"}
       end     
   end 
   
   def destroy
       @friendship.destroy
       respond_to do |format|
           format.html {redirect_to users_path, notice: "Friendship Deleted"}
       end
   end 
   
   def accept
        @friendship.accept_friendship
        @friendship.create_activity key: 'friendship.accepted' , owner: @friendship.user , recipient: @friendship.friend
        respond_to do |format|
           format.html {redirect_to users_path, notice: "Friendship Accepted"}
       end
   end
   
   private
   
   def set_user
      @user = User.find(params[:user_id]) 
      
   end 
   
   def set_friendship
       @friendship = Friendship.find(params[:id])
       
   end       
    
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to activities_path
    end  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post, only: [:edit,:destroy,:update]
    before_action :authenticate_user!
    
    def create
       @post = current_user.posts.new(post_params)
        if @post.save
            @post.create_activity key: 'post.created', owner: @post.user
           respond_to do |format|
               format.html {redirect_to user_path(@post.user.username) , notice: "Post Created" }
            end 
        else
            redirect_to user_path(@post.user.username), notice: "Error"
        end    
            
    end 
    
    def edit
        
    end  
    
    def update
        if @post.update
           respond_to do |format|
               format.html {redirect_to user_path(@post.user.username) , notice: "Post Updated" }
            end 
        else
            redirect_to post_path(@post), notice: "Error"
        end    
            
    end    
        
    
    def destroy
        @post.destroy
        respond_to do |format|
               format.html {redirect_to user_path(@post.user.username) , notice: "Post Deleted" }
            end
    end   
    
    private
    
    def set_post
       @post = Post.find(params[:id]) 
    end    
    
    def post_params
       params.require(:post).permit(:content) 
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:index]
  before_action :set_user , only: [:show]
  before_action :set_friends_count , only: [:index]
  
  def index
    case params[:people] when "friends"
      @users = current_user.active_friends
    when "requests"
      @users = current_user.pending_request_from.map(&:user)
    when "pending"
      @users = current_user.pending_request_to.map(&:friend)
    else
      @users = User.where.not(id: current_user.id)
    end  
  end  
  
  def show
    @post = Post.new
    @posts = @user.posts.order("created_at DESC")
    @activities = PublicActivity::Activity.where(owner_id: @user.id).order("created_at DESC")
  end
  
  private
  
  def set_friends_count
    @friends_count = current_user.active_friends.size
    @pending_request_count = current_user.pending_request_to.map(&:friend).size
  end

  
  def set_user
    @user = User.find_by(username: params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def action_buttons(user)
        case current_user.friendship_status(user) when "friends"
            link_to "Cancel Friendship" , friendship_path(current_user.friendship_relation(user)) , method: :delete
        when "pending"
            link_to "Cancel Request" , friendship_path(current_user.friendship_relation(user)) , method: :delete
        when "requested"
            link_to "Accept" , accept_friendship_path(current_user.friendship_relation(user)) , method: :put
            
        when "not_friends"
            link_to "Add as Friend" , friendships_path(user_id: user.id), method: :post
        end
    end    
end

app/views/activities/index.html.erb
<div class="jumborton text-center">
    <h1>Timeline</h1>
    <div class="btn-group" role="group" aria-label="Default">
        <%= link_to "Everything" , activities_path , class: "btn btn-default #{'active' unless params[:content]}" %>
        <%= link_to "Just Posts" , activities_path(content: "posts") , class: "btn btn-default #{'active' if params[:content] == 'posts'}" %>
    </div>
</div>

<div class="container">
    <ul class="timeline">
        
        <% @activities.each_with_index do |activity| %>
        <% unless activity.trackable_type == "Friendship" && activity.owner == current_user %>
        <% if activity.trackable %>
        
        <% if cycle('odd','even') == 'odd' %>
        <li class="timeline-inverted">
        <% else %>    
        <li>
        <% end %>
        <div class="timeline-badge"> (+) </div>
        <div class="timeline-panel">
            <div class="timeline-heading">
                <h4 class="timeline-title"><%= link_to activity.owner.username , user_path(activity.owner.username) %></h4>
                <p><small><%= time_ago_in_words(activity.created_at) %></small></p>
            </div>
            <div class="timeline-body">
                <% case activity.trackable_type when 'Post' %>
                <p><%= raw(activity.trackable.content_html) %>
                <% when 'Friendship' %>
                <%= link_to activity.owner.username , user_path(activity.owner.username) %> is now friends with
                <%= link_to activity.recipient.username, user_path(activity.recipient.username) %>
                 
                
                <% end %>
            </div>
        </div>
        <% end %>
        </li>
        <% end %>
        <% end %>
        
        
    </ul>
</div>

app/views/layouts/_messages.html.erb
<div>
  <% flash.each do |name,msg| %>
    <div class="alert alert-success alert-dismissible">
         <button class="close" data-dismiss="alert">X</button> 
         <%= msg %>
    </div>
  <% end %>  
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
      <%= link_to "Friend Book" , root_path , class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      
      
     

      

      
      <ul class="nav navbar-nav navbar-right">
          
        <% if user_signed_in? %>
            <li>
              <%= link_to "Timeline" , activities_path %>
            </li>
            <li>
               <li><%= link_to "People (#{friend_request_count})", users_path %></li>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.username %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile" , user_path(current_user.username) %></li>
                <li><%= link_to "My Friends" , users_path(people: "friends") %></li>
                <li><%= link_to "Account" ,edit_user_registration_path  %> </li>
                <li><%= link_to "Sign out" ,destroy_user_session_path , method: :delete , data: {confirm: "Wanna Log out ?"}  %></li>
              </ul>
            </li>
            
          
            
            
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path  %> 
            </li>
            <li><li><%= link_to "Log In" , user_session_path  %> 
            </li>
        
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/navbar' %>

<%= render 'layouts/messages' %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="row text-center">
        <div class="jumbotron front-title">
            <h1>Welcome to TalentShare</h1>
            <h3>Showcase your talents and show people what You have got</h3>
            <%= link_to "Signup" , new_user_registration_path , class: "btn btn-primary btn-lg" %>
        </div>        
    </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<div class="panel panel-info">
    <div class="panel panel-heading">
        Posts
    </div>
    <div class="panel panel-body">
        <%= f.error_notification %>
        <%= f.input :content, required: true , label: false, placeholder: "New Post content here" , input_html: {class: "fomr-control"} %>
    </div>    
        <div class="panel panel-footer">
            <%= f.button :submit, class: "btn btn-primary btn-block" %>
        </div>
    
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
    <div class="panel panel-heading">
        <%= post.user.username %> posted this about <%= time_ago_in_words(post.created_at) %> ago 
        <% if current_user && current_user == post.user %>
        <%= link_to "edit", edit_post_path(post) %> | <%= link_to "x", post_path(post) , method: :delete %>
        <% end %>
    </div>
    <div class="panel panel-body">
        <%= raw(post.content_html) %>
    </div>
    
</div>

app/views/posts/edit.html.erb
<div class="container">
   <%= "render/form" %> 
</div>

app/views/public_activity/friendship/_accepted.html.erb
<% if activity.trackable %>
    <p><%= link_to activity.owner.username , user_path(activity.owner.username) %> is now friends with 
    <%= link_to activity.recipient.username , user_path(activity.recipient.username) %></p>
<% end %>

app/views/public_activity/post/_created.html.erb
<% if activity.trackable %>
    <p><%= link_to activity.owner.username , user_path(activity.owner.username) %> posted something
    <%= time_ago_in_words(activity.created_at) %></p>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-3">
    <div class="thumbnail">
        <div class="caption">
            <h3><%= link_to user.username , user_path(user.username) %></h3>
            <% if current_user %>
                <p><%= action_buttons(user)%></p>
            <% end %>    
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
    <div class="container">
    <h1>PEOPLE</h1>
    <div class="btn-group" role="group" aria-label="Default Button Group">
        
      <%= link_to "Everyone" , users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
      <%= link_to "Friends (#{@friends_count})" , users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
      <%= link_to "Requested" , users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
      <%= link_to "Pending (#{(@pending_request_count)})" , users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
     
     </div> 
    </div>
</div>

<div class="container">
    <div class="row">
        <%= render @users %>
    </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                
            </div>
            <div class="col-md-4">
                <h3><%= @user.username %></h3>
                <h4>Age: <%= @user.age %> </h4>
                <h4>Gender: <%= @user.gender %></h4>
            </div>
            <div class="col-md-4">
                <h3>Bio: <%= @user.bio %></h3>
            </div>
            
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <!--friend zone-->
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Friends (<%= @user.active_friends.size %>)
                </div>
                <div class="panel-body">
                    <% @user.active_friends.last(16).each do |user| %>
                        <%= link_to user.username , user_path(user.username) %>
                    <% end %>    
                </div>
            </div>
        </div>
        <!--post zone -->
        <div class="col-md-4">
        <% if current_user && current_user == @user %>    
            <%= render "posts/form" %>
        <% end %>    
            <%= render @posts %>
        </div>
        <!--activity zone-->
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Recent Avtivity
                </div>
                <div class="panel-body">
                    <%= render_activities(@activities) %>
                </div>
            </div>
        </div>
    </div>
</div>